import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
// import { Suspense } from "react";
import { DiVim } from "react-icons/di";

const inter = Poppins({ 
  weight: ["100", '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Dream Music",
  description: "Generated by DreamerWebdev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Suspense fallback={<div className="flex h-screen w-screen items-center justify-center text-white">Loading...</div>}> */}
          <main>
            {children}
          </main>
      </body>
    </html>
  );
}
